name: 'Helm release'
description: 'Build and release Helm packages on s3 repositories.'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  version:
    description: Override Helm chart version.
    required: false
  chart:
    description: The local Helm cart folder path.
    default: './'
    required: true
  repo:
    description: The S3 Helm repository bucket URL.
    required: true
  forceRelease:
    description: Force and replace existing release if a release with the same version already exist.
    default: 'true'
    required: true
  packageExtraArgs:
    description: Helm package command extra arguments.
    required: false
  HelmS3Version:
    description: Version of helm-s3 plugin
    default: 'v0.13.0'
    required: false
  HelmPackVersion:
    description: Version of helm-pack plugin
    default: 'v0.2.2'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.chart }}
    - ${{ inputs.repo }}
    - ${{ inputs.forceRelease }}
    - ${{ inputs.HelmS3Version }}
    - ${{ inputs.HelmPackVersion }}
